version: "3.7"

services:
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./db/db-data:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  back:
    image: "andermirik/tm-back:1"
    restart: unless-stopped
    networks:
      - default
    environment:
      DB_PORT: 5432
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db

  consul:
    image: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"

  haproxy:
      image: haproxy
      volumes:
        - ./haproxy:/usr/local/etc/haproxy
      ports:
        - "9098:8080"
        - "1936:1936"
      depends_on: 
        - consul

networks:
  default:
    name: "ihatenetworks"