spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      registerWithEureka: false
      fetchRegistry: true
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    preferIpAddress: true

zuul:
  routes:
    tm-back-team:
      path: /tm-back-team/**
      serviceId: tm-back-team
      stripPrefix: true
      sensitiveHeaders:

management:
  security:
    enabled: false

server:
  port: ${PORT:9099}

