version: "3.7"

services:
  db:
    image: postgres:13
    restart: unless-stopped
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./db/db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  service1:
    image: "andermirik/tm-back:2"
    restart: unless-stopped
    build: .
    networks:
      - default
    environment:
      DB_PORT: 5432
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 896699
    ports:
      - "8081:8080"
    depends_on:
      - db

  service2:
    image: "andermirik/tm-back:2"
    restart: unless-stopped
    build: .
    networks:
      - default
    environment:
      DB_PORT: 5432
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 896699
    ports:
      - "8082:8080"
    depends_on:
      - db

  consul:
    image: consul:1.7
    ports:
      - "8500:8500"

networks:
  default:
    name: "zerotwobestwaifu"